---
- name: Tuesday Challenge
  hosts: planetexpress:!farnsworth
  connection: ssh
  gather_facts: yes

  tasks:
   - name: print out the variable named "result"
     debug:
       var: result
    
   - name: using apt to install sl   
     apt:
        name: sl
        state: present
     register: result
